### ISSUE TITLE
Connect EyeX controller to iTrace using C++ API

### ISSUE THREAD

**Issue by jennalwise** [YsuSERESL/iTrace#30]

**Comment by jennalwise** [comment]
Because we are running out of time to get the EyeX running for Italy, I wanted to note that I am making a not "production ready" solution to fix the calibration. Right now the calibration UI must wait until receiving the go ahead from the native code's calibration callback function to continue on to the next data point (instead of moving after 2ms) or the EyeX tracker will throw an error and then the jvm will complain. My quick and dirty solution is to move after an increased amount of time (an amount of time that seems reasonable for the tracker to finish without crashing). So, this needs fixed in the future before merging into master.

**Comment by jennalwise** [comment]
I lied. The problem is when your eyes wonder off the screen during calibration not during saccades. So disregard the comment I made previously.

**Comment by jennalwise** [comment]
I forgot to send the notification... Forget my earlier ramblings. The calibration crashes randomly inside the tobii gaze API function for adding a new calibration point. The UI even waits until this function is complete and successful for the previous point before calling this function again with a new point. I will take a look at it again with fresh eyes tomorrow and probably change my reasonings again. Right now I think it has something to do with the tobii gaze API function and the eye tracker but I could be wrong.

**Comment by jennalwise** [comment]
When you press the start tracking button before letting the session info finish exporting bad stuff happens. Need to address this after the demo.

**Comment by jennalwise** [comment]
output for the right pupil diameter should be 0 but it's spitting out garbage.

**Comment by jennalwise** [comment]
DisplayCalibrationStatus doesn't work.

**Comment by bpprox22** [comment]
Updated the title to reflect that we aren't using the C# API anymore.

**Comment by bpprox22** [comment]
I created an eyeXTracker branch based on the issue30 branch to avoid collisions with Ben or Jenna working on this issue.

**Comment by onebenclark** [comment]
@jennalwise iTrace can't find libEyeXTracker. Do you know what I need to add to the java build path?

**Comment by jennalwise** [comment]
I forgot to respond to this, but in case anyone runs into this in the future:

Make sure the libEyeXTracker.dll is in the root folder of iTrace after compiling it (you will have to move it manually).

**Comment by onebenclark** [comment]
Okay, so I switch to the a 32 bit version of Eclipse, and it seemed to work briefly (I didn't get a chance to test with Eyex, but is wasn't throwing errors). 
But then I updated the branch to match master and now it throws an Unsatisfied Link error and it can't find dependent libraries. I've tried several things but it still won't work. Any suggestions?

**Comment by jennalwise** [comment]
I am also getting the same problem. I haven't update my branch with master either. Unfortunately, UnsatisfiedLinkErrors could be a lot of things, so I am working on finding the problem now. I will update you when I have a solution.

**Comment by jennalwise** [comment]
Make sure the TobiiGazeSDK32.dll is also in your root. It didn't fix my problem, but you should still make sure that is in your iTrace root folder.

**Comment by onebenclark** [comment]
This issue was merged with the issue 58 token highlighting branch.
